name: Gandhi
favicon: null
layout_spectrum: 0.7597988324705511
typography_spectrum: 0.8660900723189116
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.25372150097973645
  lightness: 0.24568248447030783
  saturation: 0.4135928356554359
  rhythmicContrast: 0.5890208790078759
purpose: []
